DROP TABLE IF EXISTS Clients;
 
CREATE TABLE Clients (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  clientCode VARCHAR(250) NOT NULL,
  clientName VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS Stocks;
 
CREATE TABLE Stocks (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  stockCode VARCHAR(250) NOT NULL,
  lastPrice VARCHAR(250) NOT NULL
);